const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"社区工作人员管理",
			            "menuJump":"列表",
			            "tableName":"gongzuorenyuan"
			        }
			    ],
			    "menu":"社区工作人员管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"家属管理",
			            "menuJump":"列表",
			            "tableName":"jiashu"
			        }
			    ],
			    "menu":"家属管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"老人管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"老人管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"医生管理",
			            "menuJump":"列表",
			            "tableName":"yisheng"
			        }
			    ],
			    "menu":"医生管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"医生预约管理",
			            "menuJump":"列表",
			            "tableName":"yishengYuyue"
			        }
			    ],
			    "menu":"医生预约管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"事宜信息管理",
                        "menuJump":"列表",
                        "tableName":"daibanshiyi"
                    }
                ],
                "menu":"事宜信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"服务项目信息管理",
                        "menuJump":"列表",
                        "tableName":"fuwuxiangmu"
                    }
                ],
                "menu":"服务项目信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"档案信息管理",
                        "menuJump":"列表",
                        "tableName":"jiankangdangan"
                    }
                ],
                "menu":"档案信息管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"公告信息管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告信息管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"事宜类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryDaibanshiyi"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"服务项目类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryFuwuxiangmu"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"健康指标管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryJiankang"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"档案类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryJiankangdangan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"公告类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"身份管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryShenfen"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"科室管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryYisheng"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"职位管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryZhiwei"
			        }
			    ],
			    "menu":"基础数据管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
            /*,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"数据备份",
			            "menuJump":"列表",
			            "tableName":"beifen"
			        },
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"数据还原",
					    "menuJump":"列表",
					    "tableName":"huanyuan"
					}
			    ],
			    "menu":"数据库管理"
			}*/
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"家属管理",
			            "menuJump":"列表",
			            "tableName":"jiashu"
			        }
			    ],
			    "menu":"家属管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"老人管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"老人管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"医生管理",
			            "menuJump":"列表",
			            "tableName":"yisheng"
			        }
			    ],
			    "menu":"医生管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"医生预约管理",
			            "menuJump":"列表",
			            "tableName":"yishengYuyue"
			        }
			    ],
			    "menu":"医生预约管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"事宜信息管理",
	                    "menuJump":"列表",
	                    "tableName":"daibanshiyi"
	                }
	            ],
	            "menu":"事宜信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"服务项目信息管理",
	                    "menuJump":"列表",
	                    "tableName":"fuwuxiangmu"
	                }
	            ],
	            "menu":"服务项目信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"档案信息管理",
	                    "menuJump":"列表",
	                    "tableName":"jiankangdangan"
	                }
	            ],
	            "menu":"档案信息管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"公告信息管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告信息管理"
			}
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"社区工作人员",
	    "tableName":"gongzuorenyuan"
	},
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"社区工作人员管理",
			            "menuJump":"列表",
			            "tableName":"gongzuorenyuan"
			        }
			    ],
			    "menu":"社区工作人员管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"家属管理",
			            "menuJump":"列表",
			            "tableName":"jiashu"
			        }
			    ],
			    "menu":"家属管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"老人管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"老人管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "审核",
			            ],
			            "menu":"医生预约管理",
			            "menuJump":"列表",
			            "tableName":"yishengYuyue"
			        }
			    ],
			    "menu":"医生预约管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"服务项目信息管理",
	                    "menuJump":"列表",
	                    "tableName":"fuwuxiangmu"
	                }
	            ],
	            "menu":"服务项目信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"档案信息管理",
	                    "menuJump":"列表",
	                    "tableName":"jiankangdangan"
	                }
	            ],
	            "menu":"档案信息管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"公告信息管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告信息管理"
			}
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"医生",
	    "tableName":"yisheng"
	},
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"社区工作人员管理",
			            "menuJump":"列表",
			            "tableName":"gongzuorenyuan"
			        }
			    ],
			    "menu":"社区工作人员管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"家属管理",
			            "menuJump":"列表",
			            "tableName":"jiashu"
			        }
			    ],
			    "menu":"家属管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"老人管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"老人管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"医生管理",
			            "menuJump":"列表",
			            "tableName":"yisheng"
			        }
			    ],
			    "menu":"医生管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"医生预约管理",
			            "menuJump":"列表",
			            "tableName":"yishengYuyue"
			        }
			    ],
			    "menu":"医生预约管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"服务项目信息管理",
	                    "menuJump":"列表",
	                    "tableName":"fuwuxiangmu"
	                }
	            ],
	            "menu":"服务项目信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"档案信息管理",
	                    "menuJump":"列表",
	                    "tableName":"jiankangdangan"
	                }
	            ],
	            "menu":"档案信息管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"公告信息管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告信息管理"
			}
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"家属",
	    "tableName":"jiashu"
	},
	
]
    }
}
export default menu;
